FILES := \
binary_notation.py \
calcsize.py \
dynamic_format.py \
hex_notation.py \
pack_count.py \
pack_unicode.py \
pack_unpack.py \
variable_packing.py \
variable_unpacking.py

include ../../examples.mk
