FILES := \
aliasing.py \
aliasing_wrong.py \
attr.py \
builtin.py \
ex_aliasing.py \
ex_circular.py \
objects.py \
save_aliasing.py \
save_builtin.py \
shared.py \
test_aliasing.py \
test_aliasing_wrong.py \
test_builtin.py

include ../../examples.mk
