FILES := \
glob_any.py \
glob_either.py \
glob_lit.py \
glob_null.py \
simpler_match.py \
test_glob_any.py \
test_glob_either.py \
test_glob_lit.py \
test_glob_null.py \
test_glob_problem.py \
test_simpler_match.py

include ../../examples.mk
