FILES := \
better_iterator.py \
callable.py \
decorator_param.py \
decorator_simple.py \
mock_context.py \
mock_object.py \
mock_time.py \
naive_iterator.py \
test_better_iterator.py \
test_naive_iterator.py \
util.py \
wrap_capture.py \
wrap_param.py

include ../../examples.mk
