# Standalone Makefile for variable role analysis using jorma.
# Run: make -f jorma.mk   Output: index.md
#
# Note: lesson TARGETS (conditional.out, loop.out, etc.) are generated by
# running template.py on .ht template files, not from standalone .py programs.
# All Python files in this directory implement the template engine itself.

THIS_DIR   := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
JORMA_ROOT := $(realpath $(THIS_DIR)../..)
JORMA      := uv run --directory $(JORMA_ROOT) jorma

PY_FILES := \
    env.py \
    example_call.py \
    expander.py \
    template.py \
    visitor.py \
    z_if.py \
    z_loop.py \
    z_num.py \
    z_var.py

.PHONY: all
all: index.md

index.md: $(PY_FILES)
	@{ \
	    printf '# Variable Role Analysis: template\n\n'; \
	    for f in $(PY_FILES); do \
	        printf '## %s\n\n```\n' "$$f"; \
	        $(JORMA) "$(THIS_DIR)$$f" 2>&1 || true; \
	        printf '```\n\n'; \
	    done; \
	} > $@

.PHONY: clean
clean:
	rm -f index.md
