# Run: make -f jorma.mk   Output: index.md
# Note: lesson TARGETS are generated by running template.py on .ht template
# files, not from standalone .py programs.  All Python files here implement
# the template engine itself.
THIS_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

LESSON   := template
PY_FILES := \
    env.py \
    example_call.py \
    expander.py \
    template.py \
    visitor.py \
    z_if.py \
    z_loop.py \
    z_num.py \
    z_var.py

include ../examples.mk
