FILES := \
callable.py \
ex_loop_globals_2.py \
find_test_funcs.py \
func_list.py \
globals.py \
globals_plus.py \
locals.py \
manual.py \
runner.py \
type_func.py \
type_int.py \
type_len.py

include ../../examples.mk
