FILES := \
blocked.py \
blocked_file.py \
cleanup.py \
file_backed.py \
interface.py \
interface_original.py \
just_dict_original.py \
just_dict_refactored.py \
record.py \
record_original.py \
show_packed_records.py \
test_db_original.py

include ../../examples.mk
